---
title: "Advanced R"
output:
  html_document:
    number_sections: yes
    theme: sandstone
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(tidy=TRUE, results='hold', fig.align='center')
```

```{r, echo=FALSE, include=FALSE}
# devtools does not seem to work with R 3.5.0. Below is a workaround - see https://github.com/r-lib/devtools/issues/1772
# library(devtools)
# assignInNamespace("version_info", c(devtools:::version_info, list("3.5" = list(version_min = "3.3.0", version_max = "99.99.99", path = "bin"))), "devtools")
# find_rtools()
# devtools::install_github("r-lib/lobstr")
library(lobstr)
# pryr package also provides tools to pry back the surface of R and dig into the details
library(pryr)
```

```{r child_YAML, child = "Names_values.Rmd", cache=TRUE}
```

```{r child_YAML, child = "Vectors.Rmd", cache=TRUE}
```

```{r child_YAML, child = "Subsetting.Rmd", cache=TRUE}
```
  
```{r child_YAML, child = "functions.Rmd", results='markup', cache=TRUE}
```

```{r child_YAML, child = "Environments.Rmd", results='markup', cache=FALSE}
```

```{r child_YAML, child = "Conditions.Rmd", results='markup'}
```


# DO RECURSIVE SUBSETTING